### PR TITLE
Add WhosAFK integration

### PR DESCRIPTION
**Pull request by MattSturgeon**
This adds a very simple method that checks if a player has been added to the `afkers` team (as done by WhosAFK).

It should be fairly simple to extend the method in the future to check other AFK plugins too, maybe even decide which AFK plugins to check in the config.

See issue #4

### CODE REVIEW

**Comment by MattSturgeon** [comment]
Any feedback would be appreciated. I have tried to keep this change simple and without drawbacks, but I am open to suggestions. :)

**Comment by MattSturgeon** [comment]
@Phoenix616 Any feedback would be appreciated. I have tried to keep this change simple and without drawbacks, but I am open to suggestions. :)

**Comment by Phoenix616** [comment]
You should directly use the methods provided by the plugin to check whether or not a player is afk and also make sure that the plugin is actually running on the server.

I'm closing this pr in favour of a more clean, future version. (Which shouldn't unnecessarily move the plugin.yml and config.yml to another location)

**Comment by MattSturgeon** [comment]
Thanks for your feedback. Moving the yml files wasn't meant to be committed, my mistake!

WhosAFK only exposes events for when a player becomes AFK and leaves AFK, so IMO this is a better solution than the one in my initial (separate) plugin.

If you were to use the events exposed by WhosAFK, you would have to keep track of which players are currently AFK.

This may be needed anyway in the future to integrate with other AFK plugins, but seems unnecessarily complicated for this case.

**Comment by Phoenix616** [comment]
It looks like you should be able to get whether or not a player is afk with
WhosAFK.playerIsAFK(Player p).

**Pull request closed without merging**
